version: "3.8"

services:
  # PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - symfony

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - symfony

  # MySQL Service
  db:
    image: mysql:5.7
    container_name: symfony_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    networks:
      - symfony

networks:
  symfony:
    driver: bridge
